---
 - name: Installation Python version récent
   become: yes
   apt: 
     name: python3
     update_cache: yes 
     state: present

 - name: Mise à jour Python
   become: yes
   apt: 
     name: python3
     state: latest

 - name: Installation gestion paquets
   become: yes
   apt:
     name: python3-pip
     state: latest

 - name: Installation des autres paquets
   become: yes
   apt:
     name: "{{ item }}"
   loop:
     - python3-venv   
     - python3-dev
     - libssl-dev
     - libffi-dev

 - name: Configuration Backend 
   include: backend.yml
... 
